// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using UrnaEletronica.Infra.Data.Context;

#nullable disable

namespace UrnaEletronica.Infra.Data.Migrations
{
    [DbContext(typeof(UrnaEletronicaContext))]
    [Migration("20221222151652_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("UrnaEletronica.Domains.Entities.Candidato", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("Candidatos");
                });

            modelBuilder.Entity("UrnaEletronica.Domains.Entities.Candidato", b =>
                {
                    b.OwnsOne("UrnaEletronica.Domains.ValueObjects.Idade", "Idade", b1 =>
                        {
                            b1.Property<Guid>("CandidatoId")
                                .HasColumnType("uuid");

                            b1.Property<int>("Numero")
                                .HasColumnType("integer")
                                .HasColumnName("Idade");

                            b1.HasKey("CandidatoId");

                            b1.ToTable("Candidatos");

                            b1.WithOwner()
                                .HasForeignKey("CandidatoId");
                        });

                    b.OwnsOne("UrnaEletronica.Domains.ValueObjects.Nome", "Nome", b1 =>
                        {
                            b1.Property<Guid>("CandidatoId")
                                .HasColumnType("uuid");

                            b1.Property<string>("PrimeiroNome")
                                .IsRequired()
                                .HasColumnType("varchar(50)")
                                .HasColumnName("PrimeiroNome");

                            b1.Property<string>("Sobrenome")
                                .IsRequired()
                                .HasColumnType("varchar(50)")
                                .HasColumnName("Sobrenome");

                            b1.HasKey("CandidatoId");

                            b1.ToTable("Candidatos");

                            b1.WithOwner()
                                .HasForeignKey("CandidatoId");
                        });

                    b.OwnsOne("UrnaEletronica.Domains.ValueObjects.Partido", "Partido", b1 =>
                        {
                            b1.Property<Guid>("CandidatoId")
                                .HasColumnType("uuid");

                            b1.Property<DateOnly>("DataCriacao")
                                .HasColumnType("date");

                            b1.Property<string>("Nome")
                                .IsRequired()
                                .HasColumnType("varchar(50)")
                                .HasColumnName("Nome");

                            b1.Property<string>("Sigla")
                                .IsRequired()
                                .HasColumnType("varchar(10)");

                            b1.HasKey("CandidatoId");

                            b1.ToTable("Candidatos");

                            b1.WithOwner()
                                .HasForeignKey("CandidatoId");
                        });

                    b.Navigation("Idade")
                        .IsRequired();

                    b.Navigation("Nome")
                        .IsRequired();

                    b.Navigation("Partido")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
